<a href="https://colab.research.google.com/github/shaparvv/shaparvv.github.io/blob/main/%D0%A8%D0%B0%D0%BF%D0%B0%D1%80%D1%8C_3%D0%BB%D0%B0%D0%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Шапарь Вдалислав ФІТ 4-6
Лабораторна робота 3
'''

In [ ]:
from google.colab import files
import pandas as pd

In [ ]:
uploaded = files.upload()

Saving data.csv to data.csv


In [ ]:
df = pd.read_csv('data.csv')
df

Phoenix Feather  Unicorn Horn  Dragon's Blood  Mermaid Tears  \
0                 2.4          18.7            18.4           27.9   
1                 2.1           6.0            15.0           13.3   
2                17.2          13.9            23.8            6.8   
3                 8.4           9.7             6.8           26.9   
4                22.1          10.8            16.4           10.5   
...               ...           ...             ...            ...   
2333              9.4           2.2            15.8            5.9   
2334             12.1           7.6            20.6            5.3   
2335             15.2          33.2             7.2           14.5   
2336              2.0          17.0            33.2           13.2   
2337              6.2           2.6            11.7           23.8   

      Fairy Dust  Goblin Toes  Witch's Brew  Griffin Claw  Troll Hair  \
0            7.9          9.6          18.3          13.2         2.5   
1           15.6         13.1          11.0           5.0         7.2   
2           10.7         15.8          19.4           2.7        15.4   
3            4.6         29.1          14.6          19.7        18.0   
4           22.0         23.4           2.6          18.2        23.8   
...          ...          ...           ...           ...         ...   
2333        29.7         18.7          11.5          13.1        15.3   
2334        18.9         19.1           9.4          11.9        21.8   
2335        16.0         16.7           1.2          32.5        34.5   
2336        29.1         35.5          19.7          30.3        30.7   
2337        11.4          7.3          26.4          18.2        14.0   

      Kraken Ink  Minotaur Horn  Basilisk Scale  Chimera Fang  Cured  
0           26.0           10.5            26.2          12.5      0  
1           26.0            1.5            13.3           6.2      0  
2           21.2           11.1            16.6          11.4      1  
3           20.8           13.6            13.9           8.1      1  
4           11.3            5.5            16.8          16.2      0  
...          ...            ...             ...           ...    ...  
2333        22.5           10.1             4.7          13.8      0  
2334        12.0           26.7             8.4          24.4      1  
2335        25.9            3.9            18.0          19.2      1  
2336         4.3           15.7            20.5           2.1      1  
2337        17.1            3.6            21.8           2.5      1  

[2338 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2338 entries, 0 to 2337
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Phoenix Feather  2338 non-null   float64
 1   Unicorn Horn     2338 non-null   float64
 2   Dragon's Blood   2338 non-null   float64
 3   Mermaid Tears    2338 non-null   float64
 4   Fairy Dust       2338 non-null   float64
 5   Goblin Toes      2338 non-null   float64
 6   Witch's Brew     2338 non-null   float64
 7   Griffin Claw     2338 non-null   float64
 8   Troll Hair       2338 non-null   float64
 9   Kraken Ink       2338 non-null   float64
 10  Minotaur Horn    2338 non-null   float64
 11  Basilisk Scale   2338 non-null   float64
 12  Chimera Fang     2338 non-null   float64
 13  Cured            2338 non-null   int64  
dtypes: float64(13), int64(1)
memory usage: 255.8 KB


In [ ]:
df.isnull().sum()


Phoenix Feather    0
Unicorn Horn       0
Dragon's Blood     0
Mermaid Tears      0
Fairy Dust         0
Goblin Toes        0
Witch's Brew       0
Griffin Claw       0
Troll Hair         0
Kraken Ink         0
Minotaur Horn      0
Basilisk Scale     0
Chimera Fang       0
Cured              0
dtype: int64

In [ ]:
df.duplicated().sum()


np.int64(0)

In [ ]:
df.describe()

Phoenix Feather  Unicorn Horn  Dragon's Blood  Mermaid Tears  \
count      2338.000000   2338.000000     2338.000000    2338.000000   
mean         15.365697     10.946749       16.115654      13.627973   
std           8.669969      7.225162        8.372518       7.545244   
min           1.000000      1.000000        1.000000       1.000000   
25%           8.500000      5.300000        9.600000       7.600000   
50%          14.700000      9.500000       15.800000      13.100000   
75%          21.300000     15.575000       22.000000      19.000000   
max          42.100000     34.100000       40.800000      35.800000   

        Fairy Dust  Goblin Toes  Witch's Brew  Griffin Claw   Troll Hair  \
count  2338.000000  2338.000000   2338.000000   2338.000000  2338.000000   
mean     15.069504    14.157271     12.328914     14.911206    16.871685   
std       8.349340     7.831476      7.709753      8.132678     9.579027   
min       1.000000     1.000000      1.000000      1.000000     1.000000   
25%       8.625000     7.900000      6.325000      8.400000     8.900000   
50%      14.500000    13.500000     11.200000     14.400000    16.300000   
75%      20.700000    19.500000     16.900000     20.500000    24.000000   
max      40.400000    37.800000     37.300000     39.400000    44.800000   

        Kraken Ink  Minotaur Horn  Basilisk Scale  Chimera Fang        Cured  
count  2338.000000    2338.000000     2338.000000   2338.000000  2338.000000  
mean     14.890590      10.916125       15.371600     12.084003     0.496578  
std       8.014197       7.045195        8.559139      8.047540     0.500095  
min       1.000000       1.000000        1.000000      1.000000     0.000000  
25%       8.800000       5.200000        8.800000      5.600000     0.000000  
50%      14.400000       9.700000       14.800000     10.500000     0.000000  
75%      20.400000      15.375000       21.100000     17.275000     1.000000  
max      39.500000      33.700000       42.000000     37.800000     1.000000

In [ ]:
df['Cured'].value_counts()

Cured
0    1177
1    1161
Name: count, dtype: int64

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Cured', data=df)
plt.title('Cured')
plt.show()

In [ ]:
# Визначення категоріальних та числових ознак
cat_features = [col for col in df if df[col].nunique() < 25]
cont_features = [col for col in df if df[col].nunique() >= 25]

# Виведення результатів
print(f'Number of categorical features: {len(cat_features)}')
print('Categorical features:', cat_features, '\n')

print(f'Number of continuous features: {len(cont_features)}')
print('Continuous features:', cont_features, '\n')

Number of categorical features: 1
Categorical features: ['Cured'] 

Number of continuous features: 13
Continuous features: ['Phoenix Feather', 'Unicorn Horn', "Dragon's Blood", 'Mermaid Tears', 'Fairy Dust', 'Goblin Toes', "Witch's Brew", 'Griffin Claw', 'Troll Hair', 'Kraken Ink', 'Minotaur Horn', 'Basilisk Scale', 'Chimera Fang'] 



In [ ]:
correlation_matrix = df.corr()
correlation_matrix.style.background_gradient(cmap='coolwarm')


In [ ]:
correlation_with_Cured = correlation_matrix['Cured'].sort_values (ascending=False)
correlation_with_Cured


Cured              1.000000
Troll Hair         0.498165
Witch's Brew       0.245993
Goblin Toes        0.046314
Chimera Fang       0.022144
Phoenix Feather    0.015931
Fairy Dust         0.015004
Minotaur Horn      0.011329
Mermaid Tears      0.009619
Griffin Claw       0.001019
Dragon's Blood    -0.007662
Unicorn Horn      -0.008239
Kraken Ink        -0.022845
Basilisk Scale    -0.052436
Name: Cured, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import TargetEncoder, StandardScaler, LabelEncoder
import torch
import torch.nn as nn
import torch.optim as optim
import warnings
# filter warnings
warnings.filterwarnings('ignore')

In [ ]:
X = df.drop('Cured', axis=1).values
y = df['Cured'].values

In [ ]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2, stratify=y)

In [ ]:
# Convert numpy arrays to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)  # Додати вимір для сумісності з BCELoss

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)  # Додати вимір для сумісності з BCELoss

In [ ]:
# Демонстрація лінійного шару
m = nn.Linear(13, 1)  # Лінійний шар з 13 входами та 1 вихід
input = torch.randn(4, 13)  # Випадковий вхідний тензор розміром (4, 13)
output = m(input)  # Обчислення виходу

print('Input:', input, f'shape {input.shape}', sep='\n')
print('\nOutput:', output, f'shape {output.shape}', sep='\n')

Input:
tensor([[-1.4188,  0.7009, -0.1422, -0.7541, -0.6640, -0.0756,  0.4879, -0.3981,
          0.7874, -0.2277,  1.1081,  1.3512,  1.5798],
        [-0.2561,  0.5697, -1.0911,  0.0910, -0.5601, -1.0015, -0.8640, -0.6437,
          1.9488,  0.5692,  1.3260,  0.7632,  1.1535],
        [-1.2234, -1.4258,  0.3524, -0.3128, -0.4922, -0.6268,  0.9172,  0.3432,
          0.3381,  0.2797,  0.6062, -1.4362,  0.8231],
        [ 0.1447,  0.1554,  0.3230, -0.9193,  1.7981,  0.1157, -0.0795, -0.8298,
         -1.1267, -0.7253, -0.2606,  2.0420, -1.6216]])
shape torch.Size([4, 13])

Output:
tensor([[-0.2275],
        [-0.0282],
        [ 0.1805],
        [ 0.9742]], grad_fn=<AddmmBackward0>)
shape torch.Size([4, 1])


In [ ]:
t = torch.randn(4)
print('Input: ', t)
print('Applying sigmoid: ', torch.sigmoid(t))

Input:  tensor([-0.0848, -1.9209, -0.2494,  1.3350])
Applying sigmoid:  tensor([0.4788, 0.1278, 0.4380, 0.7917])


In [ ]:
class LogisticRegression(nn.Module):
    def __init__(self, input_dim):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_dim, 1)  # Один вихідний нейрон для бінарної класифікації
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out

In [ ]:
# Instantiate the model
input_dim = X_train.shape[1]
model = LogisticRegression(input_dim)

# Define loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [ ]:
model.parameters

<bound method Module.parameters of LogisticRegression(
  (linear): Linear(in_features=13, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>

In [ ]:
# Навчання моделі
num_epochs = 500
for epoch in range(num_epochs):
    # Прямий прохід
    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    # Зворотний прохід і оптимізація
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 5 == 0:
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [5/500], Loss: 0.6975
Epoch [10/500], Loss: 0.6931
Epoch [15/500], Loss: 0.6887
Epoch [20/500], Loss: 0.6845
Epoch [25/500], Loss: 0.6803
Epoch [30/500], Loss: 0.6762
Epoch [35/500], Loss: 0.6723
Epoch [40/500], Loss: 0.6684
Epoch [45/500], Loss: 0.6646
Epoch [50/500], Loss: 0.6608
Epoch [55/500], Loss: 0.6572
Epoch [60/500], Loss: 0.6536
Epoch [65/500], Loss: 0.6501
Epoch [70/500], Loss: 0.6467
Epoch [75/500], Loss: 0.6434
Epoch [80/500], Loss: 0.6401
Epoch [85/500], Loss: 0.6369
Epoch [90/500], Loss: 0.6337
Epoch [95/500], Loss: 0.6307
Epoch [100/500], Loss: 0.6276
Epoch [105/500], Loss: 0.6247
Epoch [110/500], Loss: 0.6218
Epoch [115/500], Loss: 0.6190
Epoch [120/500], Loss: 0.6162
Epoch [125/500], Loss: 0.6135
Epoch [130/500], Loss: 0.6108
Epoch [135/500], Loss: 0.6082
Epoch [140/500], Loss: 0.6056
Epoch [145/500], Loss: 0.6031
Epoch [150/500], Loss: 0.6007
Epoch [155/500], Loss: 0.5983
Epoch [160/500], Loss: 0.5959
Epoch [165/500], Loss: 0.5936
Epoch [170/500], Loss: 0.5913


In [ ]:
# Тестування моделі
with torch.no_grad():
    y_pred = model(X_test).squeeze().numpy()
    y_pred = (y_pred > 0.5).astype(int)  # Використання порогу 0.5
    accuracy = accuracy_score(y_test.numpy(), y_pred)
    print('Accuracy:', accuracy)

Accuracy: 0.8055555555555556


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
X = df.drop('Cured', axis=1)
y = df['Cured']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 89.32%

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.90      0.89       231
           1       0.90      0.89      0.89       237

    accuracy                           0.89       468
   macro avg       0.89      0.89      0.89       468
weighted avg       0.89      0.89      0.89       468



In [ ]:
confusion_mat = confusion_matrix(y_test, y_pred)
print('Confusion matrix:')
print(confusion_mat)

Confusion matrix:
[[207  24]
 [ 26 211]]


In [ ]:
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_mat, annot=True, fmt='d', cmap='Blues', cbar=False, xticklabels=True, yticklabels=True)

# Додаємо заголовки
plt.title("Confusion Matrix")
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')

# Показуємо графік
plt.tight_layout()
plt.show()

In [ ]:
'''
У цій лабораторній роботі ми проаналізували дані, щоб визначити, чи вилікувалась принцеса.
Провели аналіз ознак, побудували кореляційну матрицю, навчили та оцінили модель.
езультати показали високу точність. Для перевірки стабільності створили ще одну
модель зі sklearn — обидві дали схожі результати.
Отже, модель ефективна, і принцесу вилікувано.
'''